name: "Code Glue"
description: "Write Automations and create entities in typescript."
version: "1.0.0"
slug: "code_glue"
init: false
homeassistant_api: true
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
ports:
  80/tcp: 1331
ports_description:
  80/tcp: Web interface