/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AutomationCreateRouteImport } from './routes/automation/create'
import { Route as AutomationIdRouteImport } from './routes/automation/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationCreateRoute = AutomationCreateRouteImport.update({
  id: '/automation/create',
  path: '/automation/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationIdRoute = AutomationIdRouteImport.update({
  id: '/automation/$id',
  path: '/automation/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automation/$id': typeof AutomationIdRoute
  '/automation/create': typeof AutomationCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automation/$id': typeof AutomationIdRoute
  '/automation/create': typeof AutomationCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automation/$id': typeof AutomationIdRoute
  '/automation/create': typeof AutomationCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/automation/$id' | '/automation/create'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/automation/$id' | '/automation/create'
  id: '__root__' | '/' | '/automation/$id' | '/automation/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationIdRoute: typeof AutomationIdRoute
  AutomationCreateRoute: typeof AutomationCreateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/create': {
      id: '/automation/create'
      path: '/automation/create'
      fullPath: '/automation/create'
      preLoaderRoute: typeof AutomationCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation/$id': {
      id: '/automation/$id'
      path: '/automation/$id'
      fullPath: '/automation/$id'
      preLoaderRoute: typeof AutomationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationIdRoute: AutomationIdRoute,
  AutomationCreateRoute: AutomationCreateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
